version: '3.9'

services:
  postgres:
    container_name: postgres_container_2
    image: postgres:13.3    
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
#      - .:/var/lib/postgresql/data
    ports:
      - 5432:5432
#    networks:
#      - postgres

  mainSevice:
    container_name: banner_rotation_2
    image: banner_rotation:develop    
#    networks:
#      - postgres
