[Logger]
Level = "TRACE"
LogFile="../main.log"

[DB]
DbHost="postgres_db" 
DbPort="5432"
DbName="otusfinalproj" 
DbUserName="testuser" 
DbPassward="123456"

[Http]
Host="127.0.0.1"
Port="5000"

[Bandit]
FullLearnigCount=100
PartialLearningCount=100
FinalRandomPecent=10
