[Logger]
Level="TRACE"
LogFile="../statSender.log"

[DB]
DbHost="postgres_db" 
DbPort="5432"
DbName="otusfinalproj" 
DbUserName="otusfinalproj" 
DbPassward="otusfinalproj"

[Rabbit]
uri="amqp://guest:guest@rabbitmq:5672/"
exchange="statSender"
exchangeType="direct"
queue="queue1"
bindingKey="myKey"
sleepMinutes=5 