name: Otus Project Work tests

on:
  push:

env:
  GO111MODULE: "on"

jobs:
  test_go_get:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV        

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ~1.17
  
  test_build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: make build
        run: make build
        working-directory:

  make_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ~1.17
      - name: Check out code
        uses: actions/checkout@v3
      - name: make test
        run: make test
        working-directory:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ~1.17

      - name: Check out code
        uses: actions/checkout@v3

      - name: make lint
        run: make lint